file <- read.csv("household_power_consumption.csv", sep=";", na.strings="?")
data <- subset(file, Date == "1/2/2007" | Date == "2/2/2007")
chart <- as.numeric(data$Global_active_power)
png("plot1.png", width=480, height=480)
hist(chart, col="red", main="Global Active Power", xlab="Global Active Power (kilowatts)")
dev.off()