file <- read.csv("household_power_consumption.csv", sep=";", na.strings="?")
data <- subset(file, Date == "1/2/2007" | Date == "2/2/2007")
chart <-strptime(paste(data$Date, data$Time), format="%d/%m/%Y %H:%M:%S")
png("plot3.png", width=480, height=480)
plot(x=chart, y=data[,"Sub_metering_1"], type="l",ylab="Energy sub metering", main="", xlab="")
lines(x=chart, y=data[,"Sub_metering_2"], col="red")
lines(x=chart, y=data[,"Sub_metering_3"], col="blue")
legend("topright", lty=1, col = c("black", "blue", "red"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()