file <- read.csv("household_power_consumption.csv", sep=";", na.strings="?")
data <- subset(file, Date == "1/2/2007" | Date == "2/2/2007")
chart <-strptime(paste(data$Date, data$Time), format="%d/%m/%Y %H:%M:%S")
png("plot4.png", width=480, height=480)
par(mfrow = c(2, 2))
plot(x=chart, y=data[,"Global_active_power"], type="l",ylab="Global Active Power", main="", xlab="")
plot(x=chart, y=data[,"Voltage"], type="l",ylab="Voltage", main="", xlab="datetime")
plot(x=chart, y=data[,"Sub_metering_1"], type="l",ylab="Energy sub metering", main="", xlab="")
lines(x=chart, y=data[,"Sub_metering_2"], col="red")
lines(x=chart, y=data[,"Sub_metering_3"], col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=, lwd=2.5, col=c("black", "red", "blue"), bty="o")
plot(x=chart, y=data[,"Global_reactive_power"], type="l",ylab="Global_reactive_power", main="", xlab="datetime")
dev.off()